### ISSUE TITLE
DistributionNotFound: ipaddress

### ISSUE THREAD

**Issue by caoli5288** [sorz/sstp-server#19]
Latest git version. The module ipaddress already installed by pip.
```BASH
Traceback (most recent call last):
  File "/usr/bin/sstpd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ipaddress
```

**Comment by caoli5288** [comment]
Ok I fixed it by install python-2.7
