### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by devops724** [sorz/sstp-server#59]
when i try run it on debian 11 i get this error
2023-06-19 05:55:43,720 INFO: Running without uvloop
Traceback (most recent call last):
  File "/usr/local/bin/sstpd", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/dist-packages/sstpd/__init__.py", line 9, in run
    main()
  File "/usr/local/lib/python3.9/dist-packages/sstpd/__main__.py", line 168, in main
    server = loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1460, in create_server
    infos = await tasks.gather(*fs, loop=self)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1400, in _create_server_getaddrinfo
    infos = await self._ensure_resolved((host, port), family=family,
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by tisj** [comment]
Make sure you have a valid configuration file, especially the listen= and listen_port= options should be present and have valid values for your system: an IP and (TCP) port to bind the server process to.

**Comment by tisj** [comment]
See #45, the same is mentioned.
